### PR TITLE
Added description of spherical version of NS with LES

### PR DESCRIPTION
**Pull request by marchdf**
This is documentation for pull request https://github.com/manufactured-solutions/MASA/pull/52 Please let me know if more details are necessary.

### CODE REVIEW

**Comment by roystgnr** [comment]
I was going to push the date update onto this branch, but it looks like I don't even have write access to this repo for some reason!  My commits all predate the svn->git move, I guess?  @nicholasmalaya can you fix those things?  :-D

**Comment by nicholasmalaya** [comment]
@roystgnr -- done. Remember, with great power comes great responsibility. Spiderman told me that.

**Comment by marchdf** [comment]
@nicholasmalaya added the PeleC link and the document date should be updated to be more recent.

**Comment by nicholasmalaya** [comment]
You rule. Thanks for the work.

**Pull request merged**
